export const Theme = {
  colors: {
    primary: "#fc4c02",
    primaryDark: "#c43d00",
    primaryLight: "#ffede4",
    primaryMuted: "#ffc9af",
    background: "#f2f3f5",
    surface: "#ffffff",
    text: "#15171a",
    textMuted: "#5c6370",
    border: "#e3e5e8",
    control: "#e5e7ea",
    mapTint: "#f3f3f0",
    white: "#fff",
    dark: "#000",
    gray: "#d4d4d4",
    lightGray: "#F6F6F6",
    red: "#D30000",
  },
  space: {
    xs: 4,
    s: 8,
    m: 16,
    l: 28,
    xl: 36,
  },
  fonts: {
    regular: "ubuntuRegular",
    bold: "ubuntuBold",
  },
  roundness: 8,
  radius: {
    s: 8,
    m: 12,
    l: 16,
    xl: 20,
  },
  gutter: 20,
};
